# Train Settings (基础训练参数)
model: null             # (str) path to model file, e.g. yolov8n.pt, yolov8n.yaml
data: null              # (str) path to data file, e.g. coco128.yaml
epochs: 100             # (int) number of epochs to train for
time: null              # (float) number of hours to train for
patience: 100           # (int) epochs to wait for no observable improvement for early stopping of training
batch: 16               # (int) number of images per batch (-1 for AutoBatch)
imgsz: 640              # (int) size of input images as integer
save: true              # (bool) save train checkpoints and predict results
save_period: -1         # (int) Save checkpoint every x epochs (disabled if < 1)
cache: false            # (bool) True/ram, disk or False. Use cache for data loading
device: null            # (int | str | list) device to run on, i.e. cuda device=0 or device=0,1,2,3 or device=cpu
workers: 8              # (int) number of worker threads for data loading (per RANK if DDP)
project: null           # (str) project name
name: null              # (str) experiment name
exist_ok: false         # (bool) whether to overwrite existing experiment
pretrained: true        # (bool | str) whether to use a pretrained model (bool) or a model to load weights from (str)
optimizer: auto         # (str) optimizer to use, choices=['SGD', 'Adam', 'AdamAx', 'AdamW', 'NAdam', 'RAdam', 'RMSProp', 'auto']
seed: 0                 # (int) random seed for reproducibility
deterministic: true     # (bool) whether to enable deterministic mode
single_cls: false       # (bool) train multi-class data as single-class
classes: null           # (list) filter by class: [0, 2, 3]
rect: false             # (bool) rectangular training if mode='train' or rectangular validation if mode='val'
multi_scale: false      # (bool) whether to use multi-scale during training
cos_lr: false           # (bool) use cosine learning rate scheduler
close_mosaic: 10        # (int) disable mosaic augmentation for final epochs
resume: false           # (bool) resume training from last checkpoint
amp: true               # (bool) Automatic Mixed Precision (AMP) training
fraction: 1.0           # (float) dataset fraction to train on (default is 1.0, all images in train set)
profile: false          # (bool) profile ONNX and TensorRT speeds during training for loggers
freeze: null            # (int | list) freeze first n layers, or freeze list of layer indices
lr0: 0.01               # (float) initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.01               # (float) final learning rate (lr0 * lrf)
momentum: 0.937         # (float) SGD momentum/Adam beta1
weight_decay: 0.0005    # (float) optimizer weight decay 5e-4
warmup_epochs: 3.0      # (float) warmup epochs (fractions ok)
warmup_momentum: 0.8    # (float) warmup initial momentum
warmup_bias_lr: 0.1     # (float) warmup initial bias lr
box: 7.5                # (float) box loss gain
cls: 0.5                # (float) cls loss gain (scale with pixels)
dfl: 1.5                # (float) dfl loss gain
pose: 12.0              # (float) pose loss gain
kobj: 2.0               # (float) keypoint obj loss gain
nbs: 64                 # (int) nominal batch size
overlap_mask: true      # (bool) masks should overlap during training (segment train only)
mask_ratio: 4           # (int) mask downsample ratio (segment train only)
dropout: 0.0            # (float) use dropout regularization (classify train only)
val: true               # (bool) validate/test during training
plots: false            # (bool) save plots and images during train/val
compile: false          # (bool) compile model with torch.compile() (beta)

# Augmentation Settings (数据增强与超参数)
hsv_h: 0.015            # (float) image HSV-Hue augmentation (fraction)
hsv_s: 0.7              # (float) image HSV-Saturation augmentation (fraction)
hsv_v: 0.4              # (float) image HSV-Value augmentation (fraction)
degrees: 0.0            # (float) image rotation (+/- deg)
translate: 0.1          # (float) image translation (+/- fraction)
scale: 0.5              # (float) image scale (+/- gain)
shear: 0.0              # (float) image shear (+/- deg)
perspective: 0.0        # (float) image perspective (+/- fraction), range 0-0.001
flipud: 0.0             # (float) image flip up-down (probability)
fliplr: 0.5             # (float) image flip left-right (probability)
bgr: 0.0                # (float) image channel BGR (probability)
mosaic: 1.0             # (float) image mosaic (probability)
mixup: 0.0              # (float) image mixup (probability)
cutmix: 0.0             # (float) image cutmix (probability)
copy_paste: 0.0         # (float) segment copy-paste (probability)
copy_paste_mode: flip   # (str) the copy-paste mode (flip, mixup)
auto_augment: randaugment # (str) auto augmentation policy for classification (randaugment, autoaugment, augmix)
erasing: 0.4            # (float) probability of random erasing during classification training
augmentations: null     # (list) custom albumentations list