task: train

batch: 0.9
classes: null
data: ./datasets/from_video/(splited)7.25_港科大VS新泻大学_BO2_1_0001
device: -1
imgsz : 1280

model: runs/train/yolo12s_car_dataset_split/weights/best.pt
model_name: yolo12s_finetune
noload: false


resume: false
epochs: 100
patience: 100
save: true
save_period: 10
cache: false
workers: 8
single_cls: true
freeze: null
box: 7.5
cls: 0.5
dropout: 0.0

log_level: DEBUG
log_file: car_finetune.log

save_file: car2.0
exist_ok: true

comment: finetune verison 2.0